spring:
  application:
    name: BookTable-Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: YOUR_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: yourservice@gmail.com
    password: YOUR_PASSWORD
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: YOUR_REDIS_IP
      port: 6379
      password: YOUR_PASSWORD
      timeout: 5000
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
sa-token:
  # token name
  token-name: satoken
  # token lifetime
  timeout: 2592000
  # token timeout, -1 = forever
  active-timeout: -1
  is-concurrent: false
  is-share: false
  # token style（uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: jwt
  is-log: true
  jwt-secret-key: YOUR_PASSWORD

google:
  api:
    key: "YOUR_PASSWORD"

# application.yml
aws:
  s3:
    bucket-name: BUCKET_NAME
    region: BUCKET_REGION
  credentials:
    access-key: YOUR_PASSWORD
    secret-key: YOUR_PASSWORD