spring:
  application:
    name: BookTable-Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 5000
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: false
  is-share: false
  token-style: jwt
  is-log: true
  jwt-secret-key: ${JWT_SECRET_KEY}

google:
  api:
    key: ${GOOGLE_API_KEY}

aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
    region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
